//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVDjelo
    {
        public AVDjelo()
        {
            this.Materijali = new HashSet<Materijali>();
        }
    
        public int OID { get; set; }
        public string OriginalniNaslov { get; set; }
        public string EngleskiNaslov { get; set; }
        public string HrvatskiNaslov { get; set; }
        public Nullable<bool> Debitant { get; set; }
        public string GodinaProizvodnje { get; set; }
        public string FilmskeVrste { get; set; }
        public string Zanrovi { get; set; }
        public string Porijeklo { get; set; }
        public string PorijekloSkraceno { get; set; }
        public string DrzaveZaStatistiku { get; set; }
        public string Jezici { get; set; }
        public string JeziciSkraceno { get; set; }
        public string FazaAV_Produkcije { get; set; }
        public string Sinopsis { get; set; }
        public string SinopsisENG { get; set; }
        public string SinopsisKratki { get; set; }
        public string SinopsisKratkiENG { get; set; }
        public string LogLine { get; set; }
        public string LogLineENG { get; set; }
        public string WebLinks { get; set; }
        public string TrailerLinks { get; set; }
        public string Trajanje { get; set; }
        public string UkupnaGledanost { get; set; }
        public Nullable<System.DateTime> UdistribucijiOD { get; set; }
        public Nullable<bool> DistribucijaKino { get; set; }
        public Nullable<bool> Maloprodaja { get; set; }
        public Nullable<System.DateTime> DatumZadnjePromjene { get; set; }
        public string DostupniFormati { get; set; }
        public string LokalniDistributeri { get; set; }
        public string GlobalniDistributeri { get; set; }
        public string ProdajniAgenti { get; set; }
        public string ProdukcijskeKuce { get; set; }
        public string KoProdukcija { get; set; }
        public string Redatelji { get; set; }
        public string Scenaristi { get; set; }
        public string Producenti { get; set; }
        public string KoScenaristi { get; set; }
        public string Kamera { get; set; }
        public string Kostimografi { get; set; }
        public string Glazba { get; set; }
        public string DizajnerZvuka { get; set; }
        public string AutorGlazbe { get; set; }
        public string Animatori { get; set; }
        public string DirektoriFotografije { get; set; }
        public string Scenografi { get; set; }
        public string Montazeri { get; set; }
        public string Uloge { get; set; }
        public string KompozitingArtist { get; set; }
        public string DizajnLikova { get; set; }
        public Nullable<bool> isFilmskaVrstaAnimirani { get; set; }
        public Nullable<int> SourceOID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual ICollection<Materijali> Materijali { get; set; }
    }
}
